"""add workspace member display_name

Revision ID: 510801554498
Revises: c117793691c6
Create Date: 2025-12-21 18:52:41.198932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510801554498'
down_revision: Union[str, Sequence[str], None] = 'c117793691c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_members', sa.Column('display_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_members', 'display_name')
    # ### end Alembic commands ###
