"""extractions_review_workflow

Revision ID: da361499e584
Revises: 510801554498
Create Date: 2025-12-21 19:39:30.690291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da361499e584'
down_revision: Union[str, Sequence[str], None] = '510801554498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('transcript_version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_version_id'], ['transcript_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_meeting_id'), 'extractions', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_extractions_transcript_version_id'), 'extractions', ['transcript_version_id'], unique=False)
    op.create_table('extracted_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('speaker', sa.String(length=200), nullable=True),
    sa.Column('timestamp_start', sa.String(length=32), nullable=True),
    sa.Column('timestamp_end', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('field_confidence', sa.JSON(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('review_reasons', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_items_extraction_id'), 'extracted_items', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_extracted_items_item_type'), 'extracted_items', ['item_type'], unique=False)
    op.create_table('item_edits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('edited_by', sa.Integer(), nullable=True),
    sa.Column('prev_json', sa.JSON(), nullable=False),
    sa.Column('next_json', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['extracted_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_edits_item_id'), 'item_edits', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_edits_item_id'), table_name='item_edits')
    op.drop_table('item_edits')
    op.drop_index(op.f('ix_extracted_items_item_type'), table_name='extracted_items')
    op.drop_index(op.f('ix_extracted_items_extraction_id'), table_name='extracted_items')
    op.drop_table('extracted_items')
    op.drop_index(op.f('ix_extractions_transcript_version_id'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_meeting_id'), table_name='extractions')
    op.drop_table('extractions')
    # ### end Alembic commands ###
