"""extractions_review_workflow

Revision ID: ee41fe021159
Revises: da361499e584
Create Date: 2025-12-22 17:30:11.566496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee41fe021159'
down_revision: Union[str, Sequence[str], None] = 'da361499e584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extractions', sa.Column('raw_output', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extractions', 'raw_output')
    # ### end Alembic commands ###
